import sys
import os
import random

if not os.path.isdir('combat'):
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from rnd_utils import RangedDictionary, test_range100


rnd_wands = {
    0: {
        'common': RangedDictionary({
            range(1, 8): "Acid splash",
            range(8, 15): "Create water",
            range(15, 21): "Daze",
            range(21, 29): "Detect magic",
            range(29, 35): "Ghost sound",
            range(35, 43): "Light",
            range(43, 50): "Mage hand",
            range(50, 56): "Mending",
            range(56, 61): "Message",
            range(61, 67): "Prestidigitation",
            range(67, 74): "Purify food and drink",
            range(74, 82): "Ray of frost",
            range(82, 89): "Read magic",
            range(89, 96): "Stabilize",
            range(96, 101): "Touch of fatigue",
        }),
        'uncommon': RangedDictionary({
            range(1, 7): "Arcane mark",
            range(7, 16): "Bleed",
            range(16, 23): "Dancing lights",
            range(23, 32): "Detect poison",
            range(32, 41): "Disrupt undead",
            range(41, 49): "Flare",
            range(49, 57): "Guidance",
            range(57, 66): "Know direction",
            range(66, 74): "Lullaby",
            range(74, 80): "Open/close",
            range(80, 87): "Resistance",
            range(87, 95): "Spark",
            range(95, 101): "Virtue",
        })
    },
    1: {
        'common': RangedDictionary({
            range(1, 3): "Alarm",
            range(3, 4): "Animate rope",
            range(4, 6): "Bane",
            range(6, 12): "Bless",
            range(12, 15): "Burning hands",
            range(15, 18): "Cause fear",
            range(18, 20): "Charm person",
            range(20, 22): "Color spray",
            range(22, 24): "Command",
            range(24, 25): "Comprehend languages",
            range(25, 32): "Cure light wounds",
            range(32, 34): "Disguise self",
            range(34, 38): "Divine favor",
            range(38, 39): "Endure elements",
            range(39, 42): "Enlarge person",
            range(42, 44): "Entangle",
            range(44, 46): "Expeditious retreat",
            range(46, 47): "Feather fall",
            range(47, 49): "Grease",
            range(49, 51): "Identify",
            range(51, 53): "Inflict light wounds",
            range(53, 59): "Mage armor",
            range(59, 61): "Magic fang",
            range(61, 68): "Magic missile",
            range(68, 69): "Magic stone",
            range(69, 71): "Magic weapon",
            range(71, 72): "Obscuring mist",
            range(72, 74): "Produce flame",
            range(74, 75): "Protection from chaos",
            range(75, 76): "Protection from evil",
            range(76, 77): "Protection from good",
            range(77, 78): "Protection from law",
            range(78, 80): "Ray of enfeeblement",
            range(80, 82): "Remove fear",
            range(82, 85): "Shield",
            range(85, 87): "Shield of faith",
            range(87, 88): "Shillelagh",
            range(88, 90): "Shocking grasp",
            range(90, 91): "Silent image",
            range(91, 95): "Sleep",
            range(95, 96): "Summon monster I",
            range(96, 97): "Summon nature's ally I",
            range(97, 100): "True strike",
            range(100, 101): "Unseen servant",
        }),
        'uncommon': RangedDictionary({
            range(1, 3): "Ant haul",
            range(3, 6): "Aspect of the falcon",
            range(6, 8): "Bless weapon",
            range(8, 9): "Calm animals",
            range(9, 11): "Charm animal",
            range(11, 13): "Chill touch",
            range(13, 15): "Compel hostility",
            range(15, 18): "Confusion, lesser",
            range(18, 20): "Corrosive touch",
            range(20, 22): "Deathwatch",
            range(22, 23): "Detect animals or plants",
            range(23, 24): "Detect chaos",
            range(24, 25): "Detect evil",
            range(25, 26): "Detect good",
            range(26, 27): "Detect law",
            range(27, 29): "Detect secret doors",
            range(29, 30): "Detect snares and pits",
            range(30, 32): "Detect undead",
            range(32, 36): "Doom",
            range(36, 38): "Entropic shield",
            range(38, 39): "Erase",
            range(39, 40): "Faerie fire",
            range(40, 42): "Feather step",
            range(42, 45): "Floating disk",
            range(45, 48): "Goodberry",
            range(48, 50): "Hide from animals",
            range(50, 52): "Hide from undead",
            range(52, 53): "Hideous laughter",
            range(53, 55): "Hold portal",
            range(55, 57): "Hypnotism",
            range(57, 59): "Icicle dagger",
            range(59, 61): "Ill omen",
            range(61, 64): "Jump",
            range(64, 66): "Longstrider",
            range(66, 67): "Magic aura",
            range(67, 69): "Mount",
            range(69, 70): "Obscure object",
            range(70, 72): "Pass without trace",
            range(72, 73): "Ray of sickening",
            range(73, 76): "Reduce person",
            range(76, 79): "Sanctuary",
            range(79, 81): "Shock shield",
            range(81, 84): "Speak with animals",
            range(84, 86): "Stone fist",
            range(86, 88): "Stone shield",
            range(88, 89): "Summon minor monster",
            range(89, 90): "Undetectable alignment",
            range(90, 93): "Urban grace",
            range(93, 97): "Vanish",
            range(97, 98): "Ventriloquism",
            range(98, 99): "Magic mouth",
            range(99, 100): "Bless water",
            range(100, 101): "Curse water",
        })
    },
    2: {
        'common': RangedDictionary({
            range(1, 3): "Acid arrow",
            range(3, 4): "Aid",
            range(4, 6): "Alter self",
            range(6, 8): "Barkskin",
            range(8, 11): "Bear's endurance",
            range(11, 12): "Blur",
            range(12, 15): "Bull's strength",
            range(15, 17): "Cat's grace",
            range(17, 23): "Cure moderate wounds",
            range(23, 26): "Darkness",
            range(26, 27): "Darkvision",
            range(27, 28): "Delay poison",
            range(28, 30): "Eagle's splendor",
            range(30, 31): "False life",
            range(31, 32): "Find traps",
            range(32, 33): "Flame blade",
            range(33, 34): "Flaming sphere",
            range(34, 36): "Fog cloud",
            range(36, 38): "Fox's cunning",
            range(38, 39): "Glitterdust",
            range(39, 41): "Heat metal",
            range(41, 44): "Hold person",
            range(44, 47): "Inflict moderate wounds",
            range(47, 52): "Invisibility",
            range(52, 53): "Knock",
            range(53, 55): "Levitate",
            range(55, 56): "Minor image",
            range(56, 58): "Mirror image",
            range(58, 60): "Owl's wisdom",
            range(60, 61): "Pyrotechnics",
            range(61, 62): "Remove paralysis",
            range(62, 65): "Resist energy",
            range(65, 67): "Restoration, lesser",
            range(67, 72): "Scorching ray",
            range(72, 74): "See invisibility",
            range(74, 75): "Shatter",
            range(75, 77): "Shield other",
            range(77, 79): "Silence",
            range(79, 82): "Sound burst",
            range(82, 84): "Spider climb",
            range(84, 87): "Spiritual weapon",
            range(87, 89): "Summon monster II",
            range(89, 91): "Summon nature's ally II",
            range(91, 93): "Summon swarm",
            range(93, 97): "Web",
            range(97, 98): "Whispering wind",
            range(98, 100): "Augury",
            range(100, 101): "Fire trap",
        }),
        'uncommon': RangedDictionary({
            range(1, 3): "Align weapon",
            range(3, 6): "Animal aspect",
            range(6, 7): "Animal messenger",
            range(7, 8): "Animal trance",
            range(8, 11): "Aspect of the bear",
            range(11, 14): "Bestow weapon proficiency",
            range(14, 16): "Blindness/deafness",
            range(16, 19): "Burning gaze",
            range(19, 22): "Calm emotions",
            range(22, 25): "Chill metal",
            range(25, 26): "Command undead",
            range(26, 28): "Daze monster",
            range(28, 30): "Death knell",
            range(30, 33): "Defensive shock",
            range(33, 34): "Delay pain",
            range(34, 36): "Detect thoughts",
            range(36, 40): "Disguise other",
            range(40, 43): "Effortless armor",
            range(43, 47): "Elemental touch",
            range(47, 49): "Enthrall",
            range(49, 51): "Gentle repose",
            range(51, 52): "Ghoul touch",
            range(52, 54): "Glide",
            range(54, 56): "Groundswell",
            range(56, 57): "Gust of wind",
            range(57, 58): "Hold animal",
            range(58, 60): "Hypnotic pattern",
            range(60, 61): "Locate object",
            range(61, 62): "Make whole",
            range(62, 64): "Misdirection",
            range(64, 66): "Oppressive boredom",
            range(66, 67): "Protection from arrows",
            range(67, 68): "Reduce animal",
            range(68, 70): "Rope trick",
            range(70, 73): "Scare",
            range(73, 75): "Share language",
            range(75, 77): "Soften earth and stone",
            range(77, 79): "Spectral hand",
            range(79, 81): "Status",
            range(81, 83): "Tongues",
            range(83, 85): "Touch of idiocy",
            range(85, 87): "Tree shape",
            range(87, 89): "Warp wood",
            range(89, 92): "Weapon of awe",
            range(92, 94): "Wood shape",
            range(94, 96): "Zone of truth",
            range(96, 97): "Arcane lock",
            range(97, 98): "Consecrate",
            range(98, 99): "Desecrate",
            range(99, 100): "Continual flame",
            range(100, 101): "Phantom trap",
        })
    },
    3: {
        'common': RangedDictionary({
            range(1, 3): "Beast shape I",
            range(3, 5): "Blink",
            range(5, 8): "Call lightning",
            range(8, 9): "Create food and water",
            range(9, 15): "Cure serious wounds",
            range(15, 17): "Daylight",
            range(17, 19): "Deep slumber",
            range(19, 21): "Deeper darkness",
            range(21, 26): "Dispel magic",
            range(26, 29): "Displacement",
            range(29, 35): "Fireball",
            range(35, 36): "Flame arrow",
            range(36, 38): "Fly",
            range(38, 39): "Gaseous form",
            range(39, 41): "Haste",
            range(41, 43): "Heroism",
            range(43, 46): "Inflict serious wounds",
            range(46, 48): "Invisibility purge",
            range(48, 49): "Invisibility sphere",
            range(49, 51): "Keen edge",
            range(51, 56): "Lightning bolt",
            range(56, 57): "Magic circle against chaos",
            range(57, 58): "Magic circle against evil",
            range(58, 59): "Magic circle against good",
            range(59, 60): "Magic circle against law",
            range(60, 61): "Magic fang, greater",
            range(61, 63): "Magic vestment",
            range(63, 65): "Magic weapon, greater",
            range(65, 67): "Major image",
            range(67, 71): "Prayer",
            range(71, 75): "Protection from energy",
            range(75, 76): "Remove blindness/deafness",
            range(76, 78): "Remove curse",
            range(78, 80): "Remove disease",
            range(80, 83): "Searing light",
            range(83, 84): "Sleet storm",
            range(84, 86): "Slow",
            range(86, 88): "Speak with dead",
            range(88, 90): "Stinking cloud",
            range(90, 91): "Stone shape",
            range(91, 93): "Suggestion",
            range(93, 94): "Summon monster III",
            range(94, 95): "Summon nature's ally III",
            range(95, 98): "Vampiric touch",
            range(98, 100): "Water breathing",
            range(100, 101): "Animate dead",
        }),
        'uncommon': RangedDictionary({
            range(1, 5): "Animal aspect, greater",
            range(5, 7): "Aqueous orb",
            range(7, 9): "Arcane sight",
            range(9, 12): "Archon's aura",
            range(12, 15): "Ash storm",
            range(15, 18): "Bestow curse",
            range(18, 21): "Clairaudience/clairvoyance",
            range(21, 23): "Contagion",
            range(23, 24): "Diminish plants",
            range(24, 26): "Dominate animal",
            range(26, 30): "Elemental aura",
            range(30, 31): "Explosive runes",
            range(31, 35): "Force punch",
            range(35, 36): "Halt undead",
            range(36, 38): "Helping hand",
            range(38, 41): "Hostile levitation",
            range(41, 44): "Howling agony",
            range(44, 46): "Hydraulic torrent",
            range(46, 47): "Mad monkeys",
            range(47, 50): "Meld into stone",
            range(50, 53): "Neutralize poison",
            range(53, 55): "Pain strike",
            range(55, 56): "Phantom steed",
            range(56, 58): "Plant growth",
            range(58, 61): "Poison",
            range(61, 62): "Quench",
            range(62, 66): "Rage",
            range(66, 68): "Ray of exhaustion",
            range(68, 70): "Resinous skin",
            range(70, 71): "Secret page",
            range(71, 72): "Shrink item",
            range(72, 74): "Snare",
            range(74, 75): "Speak with plants",
            range(75, 77): "Spike growth",
            range(77, 78): "Tiny hut",
            range(78, 82): "Water walk",
            range(82, 85): "Wind wall",
            range(85, 87): "Wrathful mantle",
            range(87, 88): "Illusory script",
            range(88, 90): "Nondetection",
            range(90, 92): "Glibness",
            range(92, 96): "Good hope",
            range(96, 98): "Heal mount",
            range(98, 99): "Sculpt sound",
            range(99, 100): "Glyph of warding",
            range(100, 101): "Sepia snake sigil",
        })
    },
    4: {
        'common': RangedDictionary({
            range(1, 3): "Air walk",
            range(3, 5): "Beast shape II",
            range(5, 8): "Black tentacles",
            range(8, 9): "Chaos hammer",
            range(9, 12): "Charm monster",
            range(12, 15): "Confusion",
            range(15, 17): "Crushing despair",
            range(17, 23): "Cure critical wounds",
            range(23, 25): "Death ward",
            range(25, 29): "Dimension door",
            range(29, 30): "Dimensional anchor",
            range(30, 31): "Dismissal",
            range(31, 34): "Divine power",
            range(34, 36): "Elemental body I",
            range(36, 38): "Enervation",
            range(38, 40): "Enlarge person, mass",
            range(40, 43): "Fear",
            range(43, 45): "Fire shield",
            range(45, 49): "Flame strike",
            range(49, 52): "Freedom of movement",
            range(52, 54): "Globe of invulnerability, lesser",
            range(54, 55): "Holy smite",
            range(55, 57): "Ice storm",
            range(57, 59): "Imbue with spell ability",
            range(59, 62): "Inflict critical wounds",
            range(62, 66): "Invisibility, greater",
            range(66, 67): "Order's wrath",
            range(67, 70): "Phantasmal killer",
            range(70, 71): "Resilient sphere",
            range(71, 73): "Scrying",
            range(73, 74): "Sending",
            range(74, 75): "Shout",
            range(75, 77): "Solid fog",
            range(77, 80): "Spell immunity",
            range(80, 81): "Summon monster IV",
            range(81, 82): "Summon nature's ally IV",
            range(82, 83): "Unholy blight",
            range(83, 88): "Wall of fire",
            range(88, 92): "Wall of ice",
            range(92, 94): "Divination",
            range(94, 96): "Restoration",
            range(96, 97): "Break enchantment",
            range(97, 99): "Stoneskin",
            range(99, 100): "Planar ally, lesser",
            range(100, 101): "Restoration",
        }),
        'uncommon': RangedDictionary({
            range(1, 2): "Antiplant shell",
            range(2, 5): "Arcane eye",
            range(5, 8): "Aspect of the stag",
            range(8, 12): "Ball lightning",
            range(12, 13): "Blight",
            range(13, 14): "Command plants",
            range(14, 16): "Control water",
            range(16, 19): "Darkvision, greater",
            range(19, 20): "Detect scrying",
            range(20, 21): "Discern lies",
            range(21, 25): "Dragon's breath",
            range(25, 29): "False life, greater",
            range(29, 31): "Geas, lesser",
            range(31, 35): "Ghost wolf",
            range(35, 37): "Giant vermin",
            range(37, 38): "Hallucinatory terrain",
            range(38, 39): "Illusory wall",
            range(39, 41): "Locate creature",
            range(41, 43): "Minor creation",
            range(43, 44): "Mnemonic enhancer",
            range(44, 47): "Obsidian flow",
            range(47, 49): "Rainbow pattern",
            range(49, 51): "Reduce person, mass",
            range(51, 54): "Reincarnate",
            range(54, 55): "Repel vermin",
            range(55, 57): "Ride the waves",
            range(57, 60): "Rusting grasp",
            range(60, 61): "Secure shelter",
            range(61, 64): "Shadow conjuration",
            range(64, 68): "Shadow step",
            range(68, 71): "Shocking image",
            range(71, 75): "Spike stones",
            range(75, 77): "Volcanic storm",
            range(77, 80): "Wandering star motes",
            range(80, 81): "Animal growth",
            range(81, 83): "Commune with nature",
            range(83, 84): "Dispel chaos",
            range(84, 85): "Dispel evil",
            range(85, 88): "Dominate person",
            range(88, 92): "Hold monster",
            range(92, 95): "Holy sword",
            range(95, 96): "Mark of justice",
            range(96, 98): "Modify memory",
            range(98, 99): "Tree stride",
            range(99, 100): "Zone of silence",
            range(100, 101): "Legend lore",
        })
    }
}


rnd_wands_grade = {
    #                (spell level, caster level, type)
    "lesser minor": RangedDictionary({
        range(1, 41): (0, 1),
        range(41, 101): (1, 1)
    }),
    "greater minor": RangedDictionary({
        range(1, 81): (1, 1),
        range(81, 101): (2, 3)
    }),
    "lesser medium": RangedDictionary({
        range(1, 76): (2, 3),
        range(76, 101): (3, 5)
    }),
    "greater medium": RangedDictionary({
        range(1, 21): (2, 3),
        range(21, 101): (3, 5)
    }),
    "lesser major": RangedDictionary({
        range(1, 61): (3, 5),
        range(61, 101): (4, 7)
    }),
    "greater major": RangedDictionary({
        range(1, 31): (3, 5),
        range(31, 101): (4, 7)
    })
}

rnd_wands_rarity = RangedDictionary({
    range(1, 76): "common",
    range(76, 101): "uncommon"
})


def get_wand(grade):
    d100 = lambda: (random.randint(1, 100))
    spell_lvl, caster_lvl = rnd_wands_grade[grade][d100()]

    rarity = rnd_wands_rarity[d100()]

    wand = rnd_wands[spell_lvl][rarity][d100()]

    # TO-DO: IMPLEMENT CASTER LEVEL

    return wand


if __name__ == '__main__':
    test_range100(rnd_wands_rarity)
    test_range100(rnd_wands_grade)
    test_range100(rnd_wands)

    for g in ["lesser minor", "greater minor", "lesser medium",
              "greater medium", "lesser major", "greater major"]:
        print("{}: {}".format(g, get_wand(g)))
