import sys
import os
import random

if not os.path.isdir('combat'):
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from rnd_utils import RangedDictionary, test_range100


rnd_scrolls = {
    "arcane": {
        0: {
            'common': RangedDictionary({
                range(1, 10): "Acid  splash",
                range(10, 18): "Daze ",
                range(18, 28): "Detect  magic",
                range(28, 36): "Flare ",
                range(36, 46): "Light ",
                range(46, 56): "Mage  hand",
                range(56, 64): "Mending ",
                range(64, 73): "Prestidigitation ",
                range(73, 82): "Ray  of frost",
                range(82, 92): "Read  magic",
                range(92, 101): "Touch  of fatigue",
            }),
            'uncommon': RangedDictionary({
                range(1, 8): "Arcane  mark",
                range(8, 18): "Bleed ",
                range(18, 26): "Dancing  lights",
                range(26, 36): "Detect  poison",
                range(36, 43): "Disrupt  undead",
                range(43, 52): "Ghost  sound",
                range(52, 62): "Message ",
                range(62, 69): "Open /close",
                range(69, 76): "Resistance ",
                range(76, 84): "Sift ",
                range(84, 93): "Spark ",
                range(93, 101): "Unwitting  ally",
            }),
        },
        1: {
            'common': RangedDictionary({
                range(1, 6): "Burning  hands",
                range(6, 10): "Cause  fear",
                range(10, 15): "Charm  person",
                range(15, 18): "Chill  touch",
                range(18, 22): "Disguise  self",
                range(22, 25): "Endure  elements",
                range(25, 29): "Enlarge  person",
                range(29, 33): "Expeditious  retreat",
                range(33, 37): "Grease ",
                range(37, 40): "Hypnotism ",
                range(40, 43): "Identify ",
                range(43, 49): "Mage  armor",
                range(49, 55): "Magic  missile",
                range(55, 59): "Magic  weapon",
                range(59, 63): "Obscuring  mist",
                range(63, 65): "Protection  from chaos",
                range(65, 68): "Protection  from evil",
                range(68, 70): "Protection  from good",
                range(70, 72): "Protection  from law",
                range(72, 76): "Ray  of enfeeblement",
                range(76, 81): "Shield ",
                range(81, 85): "Shocking  grasp",
                range(85, 89): "Silent  image",
                range(89, 94): "Sleep ",
                range(94, 97): "Summon  monster I",
                range(97, 101): "True  strike",
            }),
            'uncommon': RangedDictionary({
                range(1, 3): "Air  bubble",
                range(3, 7): "Alarm ",
                range(7, 9): "Animate  rope",
                range(9, 13): "Ant  haul",
                range(13, 16): "Blend ",
                range(16, 19): "Break ",
                range(19, 24): "Color  spray",
                range(24, 27): "Comprehend  languages",
                range(27, 31): "Corrosive  touch",
                range(31, 34): "Detect  secret doors",
                range(34, 37): "Detect  undead",
                range(37, 39): "Erase ",
                range(39, 41): "Flare  burst",
                range(41, 44): "Floating  disk",
                range(44, 47): "Hold  portal",
                range(47, 49): "Hydraulic  push",
                range(49, 52): "Icicle  dagger",
                range(52, 55): "Illusion  of calm",
                range(55, 59): "Jump ",
                range(59, 61): "Magic  aura",
                range(61, 64): "Mirror  strike",
                range(64, 67): "Mount ",
                range(67, 70): "Ray  of sickening",
                range(70, 72): "Reduce  person",
                range(72, 75): "Shadow  weapon",
                range(75, 78): "Shock  shield",
                range(78, 81): "Stone  fist",
                range(81, 85): "Touch  of the sea",
                range(85, 89): "Unseen  servant",
                range(89, 92): "Urban  grace",
                range(92, 97): "Vanish ",
                range(97, 99): "Ventriloquism ",
                range(99, 101): "Voice  alteration",
            }),
        },
        2: {
            'common': RangedDictionary({
                range(1, 5): "Acid  arrow",
                range(5, 8): "Alter  self",
                range(8, 13): "Bear 's endurance",
                range(13, 16): "Blur ",
                range(16, 21): "Bull 's strength",
                range(21, 25): "Cat 's grace",
                range(25, 28): "Darkness ",
                range(28, 31): "Darkvision ",
                range(31, 35): "Eagle 's splendor",
                range(35, 38): "False  life",
                range(38, 41): "Flaming  sphere",
                range(41, 45): "Fox 's cunning",
                range(45, 48): "Glitterdust ",
                range(48, 53): "Invisibility ",
                range(53, 55): "Knock ",
                range(55, 59): "Levitate ",
                range(59, 62): "Minor  image",
                range(62, 66): "Mirror  image",
                range(66, 70): "Owl 's wisdom",
                range(70, 74): "Resist  energy",
                range(74, 76): "Rope  trick",
                range(76, 81): "Scorching  ray",
                range(81, 84): "See  invisibility",
                range(84, 86): "Shatter ",
                range(86, 89): "Spider  climb",
                range(89, 92): "Summon  monster II",
                range(92, 94): "Summon  swarm",
                range(94, 99): "Web ",
                range(99, 101): "Whispering  wind",
            }),
            'uncommon': RangedDictionary({
                range(1, 4): "Bestow  weapon proficiency",
                range(4, 7): "Blindness /deafness",
                range(7, 10): "Burning  gaze",
                range(10, 13): "Certain  grip",
                range(13, 15): "Command  undead",
                range(15, 17): "Create  pit",
                range(17, 21): "Daze  monster",
                range(21, 24): "Detect  thoughts",
                range(24, 28): "Disguise  other",
                range(28, 32): "Elemental  touch",
                range(32, 35): "Fire  breath",
                range(35, 39): "Fog  cloud",
                range(39, 41): "Ghoul  touch",
                range(41, 42): "Glide ",
                range(42, 45): "Gust  of wind",
                range(45, 48): "Haunting  mists",
                range(48, 52): "Hideous  laughter",
                range(52, 55): "Hypnotic  pattern",
                range(55, 58): "Locate  object",
                range(58, 61): "Make  whole",
                range(61, 63): "Misdirection ",
                range(63, 64): "Obscure  object",
                range(64, 66): "Pernicious  poison",
                range(66, 68): "Protection  from arrows",
                range(68, 71): "Pyrotechnics ",
                range(71, 74): "Returning  weapon",
                range(74, 78): "Scare ",
                range(78, 81): "Shadow  anchor",
                range(81, 84): "Share  memory",
                range(84, 86): "Slipstream ",
                range(86, 89): "Spectral  hand",
                range(89, 91): "Spontaneous  immolation",
                range(91, 94): "Touch  of idiocy",
                range(94, 95): "Unshakable  chill",
                range(95, 97): "Magic  mouth",
                range(97, 98): "Arcane  lock",
                range(98, 100): "Continual  flame",
                range(100, 101): "Phantom  trap",
            }),
        },
        3: {
            'common': RangedDictionary({
                range(1, 4): "Beast  shape I",
                range(4, 8): "Blink ",
                range(8, 13): "Dispel  magic",
                range(13, 17): "Displacement ",
                range(17, 22): "Fireball ",
                range(22, 25): "Flame  arrow",
                range(25, 30): "Fly ",
                range(30, 33): "Gaseous  form",
                range(33, 38): "Haste ",
                range(38, 41): "Heroism ",
                range(41, 44): "Hold  person",
                range(44, 47): "Invisibility  sphere",
                range(47, 52): "Lightning  bolt",
                range(52, 55): "Magic  circle against chaos",
                range(55, 58): "Magic  circle against evil",
                range(58, 61): "Magic  circle against good",
                range(61, 64): "Magic  circle against law",
                range(64, 67): "Major  image",
                range(67, 71): "Phantom  steed",
                range(71, 75): "Protection  from energy",
                range(75, 79): "Slow ",
                range(79, 82): "Stinking  cloud",
                range(82, 85): "Suggestion ",
                range(85, 88): "Summon  monster III",
                range(88, 91): "Tiny  hut",
                range(91, 95): "Tongues ",
                range(95, 98): "Vampiric  touch",
                range(98, 101): "Water  breathing",
            }),
            'uncommon': RangedDictionary({
                range(1, 4): "Animate  dead, lesser",
                range(4, 7): "Aqueous  orb",
                range(7, 9): "Arcane  sight",
                range(9, 13): "Beast  shape",
                range(13, 16): "Clairaudience /clairvoyance",
                range(16, 18): "Cloak  of winds",
                range(18, 21): "Daylight ",
                range(21, 25): "Deep  slumber",
                range(25, 28): "Distracting  cacophony",
                range(28, 31): "Draconic  reservoir",
                range(31, 36): "Elemental  aura",
                range(36, 39): "Explosive  runes",
                range(39, 44): "Force  punch",
                range(44, 46): "Gentle  repose",
                range(46, 48): "Halt  undead",
                range(48, 50): "Healing  thief",
                range(50, 52): "Hydraulic  torrent",
                range(52, 57): "Keen  edge",
                range(57, 62): "Magic  weapon, greater",
                range(62, 66): "Monstrous  physique I",
                range(66, 69): "Rage ",
                range(69, 71): "Ray  of exhaustion",
                range(71, 74): "Resinous  skin",
                range(74, 76): "Resist  energy, communal",
                range(76, 79): "Secret  page",
                range(79, 81): "Shrink  item",
                range(81, 84): "Sleet  storm",
                range(84, 87): "Spiked  pit",
                range(87, 91): "Undead  anatomy I",
                range(91, 93): "Versatile  weapon",
                range(93, 96): "Wind  wall",
                range(96, 97): "Illusory  script",
                range(97, 100): "Nondetection ",
                range(100, 101): "Sepia  snake sigil",
            }),
        },
        4: {
            'common': RangedDictionary({
                range(1, 4): "Beast  shape II",
                range(4, 6): "Bestow  curse",
                range(6, 10): "Black  tentacles",
                range(10, 15): "Charm  monster",
                range(15, 19): "Confusion ",
                range(19, 22): "Crushing  despair",
                range(22, 27): "Dimension  door",
                range(27, 30): "Dimensional  anchor",
                range(30, 33): "Elemental  body I",
                range(33, 37): "Enervation ",
                range(37, 39): "Enlarge  person, mass",
                range(39, 44): "Fear ",
                range(44, 48): "Fire  shield",
                range(48, 51): "Globe  of invulnerability, lesser",
                range(51, 55): "Ice  storm",
                range(55, 60): "Invisibility , greater",
                range(60, 65): "Phantasmal  killer",
                range(65, 68): "Resilient  sphere",
                range(68, 72): "Scrying ",
                range(72, 75): "Shadow  conjuration",
                range(75, 77): "Shout ",
                range(77, 79): "Solid  fog",
                range(79, 81): "Stone  shape",
                range(81, 84): "Summon  monster IV",
                range(84, 89): "Wall  of fire",
                range(89, 93): "Wall  of ice",
                range(93, 98): "Stoneskin ",
                range(98, 101): "Animate  dead",
            }),
            'uncommon': RangedDictionary({
                range(1, 3): "Acid  pit",
                range(3, 7): "Arcane  eye",
                range(7, 11): "Ball  lightning",
                range(11, 14): "Contagion ",
                range(14, 18): "Darkvision , greater",
                range(18, 20): "Detect  scrying",
                range(20, 24): "Dragon 's breath",
                range(24, 29): "False  life, greater",
                range(29, 33): "Firefall ",
                range(33, 36): "Geas , lesser",
                range(36, 40): "Ghost  wolf",
                range(40, 42): "Hallucinatory  terrain",
                range(42, 44): "Illusory  wall",
                range(44, 47): "Locate  creature",
                range(47, 51): "Minor  creation",
                range(51, 55): "Monstrous  physique II",
                range(55, 58): "Obsidian  flow",
                range(58, 60): "Phantom  chariot",
                range(60, 63): "Rainbow  pattern",
                range(63, 65): "Reduce  person, mass",
                range(65, 69): "Remove  curse",
                range(69, 72): "Secure  shelter",
                range(72, 75): "Shadow  projection",
                range(75, 80): "Shocking  image",
                range(80, 84): "Telekinetic  charge",
                range(84, 86): "True  form",
                range(86, 90): "Vermin  shape I",
                range(90, 95): "Volcanic  storm",
                range(95, 98): "Wandering  star motes",
                range(98, 100): "Fire  trap",
                range(100, 101): "Mnemonic  enhancer",
            }),
        },
        5: {
            'common': RangedDictionary({
                range(1, 4): "Baleful  polymorph",
                range(4, 8): "Beast  shape III",
                range(8, 11): "Break  enchantment",
                range(11, 16): "Cloudkill ",
                range(16, 22): "Cone  of cold",
                range(22, 24): "Contact  other plane",
                range(24, 27): "Dismissal ",
                range(27, 32): "Dominate  person",
                range(32, 36): "Feeblemind ",
                range(36, 41): "Hold  monster",
                range(41, 44): "Magic  jar",
                range(44, 47): "Mind  fog",
                range(47, 52): "Overland  flight",
                range(52, 55): "Passwall ",
                range(55, 57): "Permanency ",
                range(57, 59): "Planar  binding, lesser",
                range(59, 63): "Polymorph ",
                range(63, 66): "Sending ",
                range(66, 70): "Shadow  evocation",
                range(70, 74): "Summon  monster V",
                range(74, 77): "Telekinesis ",
                range(77, 83): "Teleport ",
                range(83, 89): "Wall  of force",
                range(89, 93): "Wall  of stone",
                range(93, 96): "Waves  of fatigue",
                range(96, 98): "Symbol  of pain",
                range(98, 101): "Symbol  of sleep",
            }),
            'uncommon': RangedDictionary({
                range(1, 3): "Absorb  toxicity",
                range(3, 5): "Animal  growth",
                range(5, 7): "Blight ",
                range(7, 10): "Dream ",
                range(10, 14): "Elemental  body II",
                range(14, 16): "Fabricate ",
                range(16, 20): "Fire  snake",
                range(20, 23): "Hostile  juxtaposition",
                range(23, 26): "Hungry  pit",
                range(26, 30): "Icy  prison",
                range(30, 34): "Interposing  hand",
                range(34, 37): "Life  bubble",
                range(37, 39): "Mage 's faithful hound",
                range(39, 41): "Mage 's private sanctum",
                range(41, 44): "Major  creation",
                range(44, 47): "Mirage  arcana",
                range(47, 51): "Monstrous  physique III",
                range(51, 55): "Nightmare ",
                range(55, 57): "Persistent  image",
                range(57, 61): "Planar  adaptation",
                range(61, 65): "Plant  shape I",
                range(65, 69): "Prying  eyes",
                range(69, 71): "Secret  chest",
                range(71, 74): "Seeming ",
                range(74, 77): "Sonic  thrust",
                range(77, 80): "Suffocation ",
                range(80, 83): "Telepathic  bond",
                range(83, 85): "Transmute  mud to rock",
                range(85, 87): "Transmute  rock to mud",
                range(87, 91): "Undead  anatomy II",
                range(91, 95): "Vermin  form II",
                range(95, 99): "Wind  blades",
                range(99, 101): "False  vision",
            }),
        },
        6: {
            'common': RangedDictionary({
                range(1, 4): "Acid  fog",
                range(4, 8): "Antimagic  field",
                range(8, 11): "Bear 's endurance, mass",
                range(11, 14): "Beast  shape IV",
                range(14, 17): "Bull 's strength, mass",
                range(17, 20): "Cat 's grace, mass",
                range(20, 26): "Chain  lightning",
                range(26, 32): "Disintegrate ",
                range(32, 38): "Dispel  magic, greater",
                range(38, 41): "Eagle 's splendor, mass",
                range(41, 43): "Eyebite ",
                range(43, 48): "Flesh  to stone",
                range(48, 51): "Form  of the dragon I",
                range(51, 54): "Fox 's cunning, mass",
                range(54, 57): "Globe  of invulnerability",
                range(57, 60): "Heroism , greater",
                range(60, 63): "Mislead ",
                range(63, 66): "Owl 's wisdom, mass",
                range(66, 68): "Planar  binding",
                range(68, 71): "Shadow  walk",
                range(71, 73): "Stone  to flesh",
                range(73, 77): "Suggestion , mass",
                range(77, 80): "Summon  monster VI",
                range(80, 83): "Transformation ",
                range(83, 85): "Veil ",
                range(85, 88): "Wall  of iron",
                range(88, 90): "Create  undead",
                range(90, 93): "Legend  lore",
                range(93, 97): "True  seeing",
                range(97, 99): "Circle  of death",
                range(99, 101): "Symbol  of fear",
            }),
            'uncommon': RangedDictionary({
                range(1, 5): "Analyze  dweomer",
                range(5, 9): "Battlemind  link",
                range(9, 13): "Cloak  of dreams",
                range(13, 16): "Contagion , greater",
                range(16, 21): "Contagious  flame",
                range(21, 27): "Contingency ",
                range(27, 31): "Control  water",
                range(31, 36): "Elemental  body III",
                range(36, 40): "Fluid  form",
                range(40, 46): "Forceful  hand",
                range(46, 49): "Freezing  sphere",
                range(49, 54): "Geas /quest",
                range(54, 58): "Getaway ",
                range(58, 60): "Guards  and wards",
                range(60, 62): "Mage 's lucubration",
                range(62, 67): "Monstrous  physique IV",
                range(67, 69): "Move  earth",
                range(69, 72): "Permanent  image",
                range(72, 77): "Plant  shape II",
                range(77, 81): "Repulsion ",
                range(81, 85): "Sirocco ",
                range(85, 88): "Tar  pool",
                range(88, 93): "Undead  anatomy III",
                range(93, 96): "Programmed  image",
                range(96, 99): "Undeath  to death",
                range(99, 101): "Symbol  of persuasion",
            }),
        },
        7: {
            'common': RangedDictionary({
                range(1, 5): "Arcane  sight, greater",
                range(5, 8): "Banishment ",
                range(8, 14): "Delayed  blast fireball",
                range(14, 18): "Ethereal  jaunt",
                range(18, 23): "Finger  of death",
                range(23, 28): "Form  of the dragon II",
                range(28, 31): "Hold  person, mass",
                range(31, 36): "Invisibility , mass",
                range(36, 40): "Mage 's sword",
                range(40, 43): "Phase  door",
                range(43, 49): "Plane  shift",
                range(49, 54): "Polymorph , greater",
                range(54, 58): "Power  word blind",
                range(58, 63): "Prismatic  spray",
                range(63, 67): "Reverse  gravity",
                range(67, 71): "Scrying , greater",
                range(71, 74): "Shadow  conjuration, greater",
                range(74, 79): "Spell  turning",
                range(79, 82): "Summon  monster VII",
                range(82, 88): "Teleport , greater",
                range(88, 91): "Waves  of exhaustion",
                range(91, 94): "Project  image",
                range(94, 98): "Forcecage ",
                range(98, 101): "Limited  wish",
            }),
            'uncommon': RangedDictionary({
                range(1, 4): "Control  undead",
                range(4, 8): "Control  weather",
                range(8, 11): "Create  demiplane, lesser",
                range(11, 15): "Deflection ",
                range(15, 20): "Elemental  body IV",
                range(20, 24): "Firebrand ",
                range(24, 30): "Fly , mass",
                range(30, 35): "Giant  form I",
                range(35, 41): "Grasping  hand",
                range(41, 45): "Hostile  juxtaposition, greater",
                range(45, 50): "Ice  body",
                range(50, 54): "Insanity ",
                range(54, 57): "Mage 's magnificent mansion",
                range(57, 62): "Phantasmal  revenge",
                range(62, 66): "Plague  storm",
                range(66, 71): "Plant  shape III",
                range(71, 75): "Resonating  word",
                range(75, 79): "Sequester ",
                range(79, 82): "Statue ",
                range(82, 85): "Teleport  object",
                range(85, 89): "Walk  through space",
                range(89, 92): "Vision ",
                range(92, 94): "Instant  summons",
                range(94, 97): "Symbol  of stunning",
                range(97, 99): "Symbol  of weakness",
                range(99, 101): "Simulacrum ",
            }),
        },
        8: {
            'common': RangedDictionary({
                range(1, 6): "Charm  monster, mass",
                range(6, 10): "Demand ",
                range(10, 14): "Dimensional  lock",
                range(14, 19): "Form  of the dragon III",
                range(19, 24): "Horrid  wilting",
                range(24, 29): "Incendiary  cloud",
                range(29, 34): "Irresistible  dance",
                range(34, 41): "Maze ",
                range(41, 46): "Mind  blank",
                range(46, 50): "Planar  binding, greater",
                range(50, 56): "Polar  ray",
                range(56, 60): "Polymorph  any object",
                range(60, 67): "Power  word stun",
                range(67, 73): "Prismatic  wall",
                range(73, 77): "Scintillating  pattern",
                range(77, 81): "Summon  monster VIII",
                range(81, 86): "Telekinetic  sphere",
                range(86, 91): "Protection  from spells",
                range(91, 95): "Symbol  of death",
                range(95, 98): "Temporal  stasis",
                range(98, 101): "Trap  the soul",
            }),
            'uncommon': RangedDictionary({
                range(1, 5): "Antipathy ",
                range(5, 11): "Clenched  fist",
                range(11, 13): "Clone ",
                range(13, 16): "Create  demiplane",
                range(16, 20): "Discern  location",
                range(20, 25): "Euphoric  tranquility",
                range(25, 30): "Frightful  aspect",
                range(30, 35): "Giant  form II",
                range(35, 39): "Iron  body",
                range(39, 44): "Moment  of prescience",
                range(44, 48): "Orb  of the void",
                range(48, 53): "Pyrying  eyes, greater",
                range(53, 57): "Screen ",
                range(57, 63): "Shadow  evocation, greater",
                range(63, 67): "Shout , greater",
                range(67, 73): "Stormbolts ",
                range(73, 77): "Sunburst ",
                range(77, 82): "Undead  anatomy IV",
                range(82, 88): "Wall  of lava",
                range(88, 92): "Create  greater undead",
                range(92, 96): "Sympathy ",
                range(96, 99): "Symbol  of insanity",
                range(99, 101): "Binding  (chaining)",
            }),
        },
        9: {
            'common': RangedDictionary({
                range(1, 7): "Dominate  monster",
                range(7, 12): "Energy  drain",
                range(12, 17): "Freedom ",
                range(17, 24): "Gate ",
                range(24, 29): "Hold  monster, mass",
                range(29, 34): "Imprisonment ",
                range(34, 40): "Mage 's disjunction",
                range(40, 48): "Meteor  swarm",
                range(48, 56): "Power  word kill",
                range(56, 62): "Prismatic  sphere",
                range(62, 67): "Shapechange ",
                range(67, 72): "Summon  monster IX",
                range(72, 80): "Time  stop",
                range(80, 86): "Weird ",
                range(86, 91): "Astral  projection",
                range(91, 97): "Teleportation  circle",
                range(97, 101): "Wish ",
            }),
            'uncommon': RangedDictionary({
                range(1, 7): "Create  demiplane, greater",
                range(7, 16): "Crushing  hand",
                range(16, 24): "Etherealness ",
                range(24, 32): "Fiery  body",
                range(32, 39): "Foresight ",
                range(39, 45): "Heroic  invocation",
                range(45, 51): "Icy  prison, mass",
                range(51, 58): "Ride  the lightning",
                range(58, 66): "Shades ",
                range(66, 73): "Soul  bind",
                range(73, 80): "Tsunami ",
                range(80, 89): "Wail  of the banshee",
                range(89, 96): "Winds  of vengeance",
                range(96, 101): "Refuge ",
            }),
        }
    },
    "divine": {
        0: {
            'common': RangedDictionary({
                range(1, 12): "Bleed ",
                range(12, 22): "Create  water",
                range(22, 35): "Detect  magic",
                range(35, 45): "Know  direction",
                range(45, 56): "Light ",
                range(56, 66): "Mending ",
                range(66, 76): "Purify  food and drink",
                range(76, 89): "Read  magic",
                range(89, 101): "Stabilize ",
            }),
            'uncommon': RangedDictionary({
                range(1, 16): "Detect  poison",
                range(16, 34): "Flare ",
                range(34, 51): "Guidance ",
                range(51, 69): "Resistance ",
                range(69, 86): "Spark ",
                range(86, 101): "Virtue ",
            }),
        },
        1: {
            'common': RangedDictionary({
                range(1, 5): "Bane ",
                range(5, 11): "Bless ",
                range(11, 16): "Cause  fear",
                range(16, 20): "Command ",
                range(20, 23): "Comprehend  languages",
                range(23, 29): "Cure  light wounds",
                range(29, 31): "Detect  chaos",
                range(31, 33): "Detect  evil",
                range(33, 35): "Detect  good",
                range(35, 37): "Detect  law",
                range(37, 40): "Detect  undead",
                range(40, 46): "Divine  favor",
                range(46, 49): "Doom ",
                range(49, 53): "Entangle ",
                range(53, 58): "Inflict  light wounds",
                range(58, 62): "Magic  fang",
                range(62, 66): "Obscuring  mist",
                range(66, 69): "Produce  flame",
                range(69, 72): "Protection  from chaos",
                range(72, 75): "Protection  from evil",
                range(75, 78): "Protection  from good",
                range(78, 81): "Protection  from law",
                range(81, 85): "Remove  fear",
                range(85, 89): "Sanctuary ",
                range(89, 95): "Shield  of faith",
                range(95, 98): "Summon  monster I",
                range(98, 101): "Summon  nature's ally I",
            }),
            'uncommon': RangedDictionary({
                range(1, 5): "Ant  haul",
                range(5, 8): "Aspect  of the falcon",
                range(8, 10): "Calm  animals",
                range(10, 13): "Charm  animal",
                range(13, 16): "Compel  hostility",
                range(16, 18): "Deathwatch ",
                range(18, 19): "Detect  animals or plants",
                range(19, 21): "Detect  snares and pits",
                range(21, 24): "Diagnose  disease",
                range(24, 28): "Endure  elements",
                range(28, 31): "Entropic  shield",
                range(31, 34): "Faerie  fire",
                range(34, 37): "Feather  step",
                range(37, 40): "Forbid  action",
                range(40, 43): "Frostbite ",
                range(43, 47): "Goodberry ",
                range(47, 48): "Hide  from animals",
                range(48, 50): "Hide  from undead",
                range(50, 53): "Hydraulic  push",
                range(53, 56): "Jump ",
                range(56, 60): "Keen  senses",
                range(60, 63): "Liberating  command",
                range(63, 66): "Longstrider ",
                range(66, 69): "Magic  stone",
                range(69, 73): "Pass  without trace",
                range(73, 75): "Remove  sickness",
                range(75, 76): "Sanctify  corpse",
                range(76, 79): "Shillelagh ",
                range(79, 82): "Speak  with animals",
                range(82, 86): "Stone  fist",
                range(86, 89): "Stone  shield",
                range(89, 92): "Sun  metal",
                range(92, 96): "Touch  of the sea",
                range(96, 99): "Bless  water",
                range(99, 101): "Curse  water",
            }),
        },
        2: {
            'common': RangedDictionary({
                range(1, 5): "Aid ",
                range(5, 7): "Align  weapon",
                range(7, 9): "Animal  messenger",
                range(9, 14): "Barkskin ",
                range(14, 17): "Bear 's endurance",
                range(17, 20): "Bull 's strength",
                range(20, 23): "Cat 's grace",
                range(23, 25): "Chill  metal",
                range(25, 31): "Cure  moderate wounds",
                range(31, 34): "Darkness ",
                range(34, 37): "Delay  poison",
                range(37, 40): "Eagle 's splendor",
                range(40, 42): "Find  traps",
                range(42, 45): "Flame  blade",
                range(45, 47): "Fog  cloud",
                range(47, 51): "Heat  metal",
                range(51, 53): "Hold  animal",
                range(53, 57): "Hold  person",
                range(57, 61): "Inflict  moderate wounds",
                range(61, 64): "Owl 's wisdom",
                range(64, 66): "Remove  paralysis",
                range(66, 69): "Resist  energy",
                range(69, 74): "Restoration , lesser",
                range(74, 78): "Shield  other",
                range(78, 82): "Silence ",
                range(82, 86): "Sound  burst",
                range(86, 90): "Spiritual  weapon",
                range(90, 92): "Summon  monster II",
                range(92, 94): "Summon  nature's ally II",
                range(94, 96): "Summon  swarm",
                range(96, 98): "Zone  of truth",
                range(98, 101): "Augury ",
            }),
            'uncommon': RangedDictionary({
                range(1, 5): "Animal  aspect",
                range(5, 7): "Animal  trance",
                range(7, 11): "Animate  dead, lesser",
                range(11, 14): "Arrow  of law",
                range(14, 18): "Aspect  of the bear",
                range(18, 21): "Blessing  of courage and life",
                range(21, 25): "Calm  emotions",
                range(25, 28): "Death  knell",
                range(28, 31): "Dread  bolt",
                range(31, 35): "Effortless  armor",
                range(35, 38): "Enthrall ",
                range(38, 42): "Flaming  sphere",
                range(42, 44): "Gentle  repose",
                range(44, 47): "Grace ",
                range(47, 49): "Groundswell ",
                range(49, 52): "Gust  of wind",
                range(52, 54): "Instant  armor",
                range(54, 56): "Instrument  of agony",
                range(56, 59): "Make  whole",
                range(59, 61): "Reduce  animal",
                range(61, 63): "Scent  trail",
                range(63, 66): "Shard  of chaos",
                range(66, 69): "Share  language",
                range(69, 71): "Shatter ",
                range(71, 74): "Soften  earth and stone",
                range(74, 77): "Spear  of purity",
                range(77, 80): "Spider  climb",
                range(80, 83): "Status ",
                range(83, 85): "Tree  shape",
                range(85, 86): "Undetectable  alignment",
                range(86, 89): "Warp  wood",
                range(89, 92): "Weapon  of awe",
                range(92, 94): "Wood  shape",
                range(94, 96): "Consecrate ",
                range(96, 98): "Desecrate ",
                range(98, 100): "Fire  trap",
                range(100, 101): "Masterwork  transformation",
            }),
        },
        3: {
            'common': RangedDictionary({
                range(1, 4): "Bestow  curse",
                range(4, 9): "Call  lightning",
                range(9, 16): "Cure  serious wounds",
                range(16, 20): "Daylight ",
                range(20, 24): "Deeper  darkness",
                range(24, 29): "Dispel  magic",
                range(29, 34): "Inflict  serious wounds",
                range(34, 38): "Invisibility  purge",
                range(38, 41): "Locate  object",
                range(41, 43): "Magic  circle against chaos",
                range(43, 45): "Magic  circle against evil",
                range(45, 47): "Magic  circle against good",
                range(47, 49): "Magic  circle against law",
                range(49, 53): "Magic  fang, greater",
                range(53, 58): "Magic  vestment",
                range(58, 60): "Poison ",
                range(60, 66): "Prayer ",
                range(66, 69): "Protection  from energy",
                range(69, 71): "Remove  blindness/deafness",
                range(71, 74): "Remove  curse",
                range(74, 77): "Remove  disease",
                range(77, 80): "Searing  light",
                range(80, 82): "Sleet  storm",
                range(82, 86): "Speak  with dead",
                range(86, 88): "Stone  shape",
                range(88, 90): "Summon  monster III",
                range(90, 92): "Summon  nature's ally III",
                range(92, 96): "Water  breathing",
                range(96, 98): "Water  walk",
                range(98, 101): "Animate  dead",
            }),
            'uncommon': RangedDictionary({
                range(1, 5): "Aqueous  orb",
                range(5, 9): "Archon 's aura",
                range(9, 13): "Bestow  insight",
                range(13, 17): "Blindness /deafness",
                range(17, 20): "Burst  of nettles",
                range(20, 23): "Chain  of perdition",
                range(23, 27): "Contagion ",
                range(27, 31): "Create  food and water",
                range(31, 35): "Daybreak  arrow",
                range(35, 37): "Diminish  plants",
                range(37, 41): "Discovery  torch",
                range(41, 46): "Dominate  animal",
                range(46, 49): "Guiding  star",
                range(49, 52): "Helping  hand",
                range(52, 57): "Meld  into stone",
                range(57, 59): "Obscure  object",
                range(59, 62): "Plant  growth",
                range(62, 65): "Quench ",
                range(65, 68): "Shifting  sands",
                range(68, 73): "Snare ",
                range(73, 76): "Speak  with plants",
                range(76, 81): "Spike  growth",
                range(81, 84): "Vision  of hell",
                range(84, 88): "Wind  wall",
                range(88, 91): "Wrathful  mantle",
                range(91, 94): "Continual  flame",
                range(94, 97): "Nap  stack",
                range(97, 99): "Glyph  of warding",
                range(99, 101): "Symbol  of healing",
            }),
        },
        4: {
            'common': RangedDictionary({
                range(1, 5): "Air  walk",
                range(5, 8): "Chaos  hammer",
                range(8, 16): "Cure  critical wounds",
                range(16, 20): "Death  ward",
                range(20, 23): "Dimensional  anchor",
                range(23, 26): "Discern  lies",
                range(26, 29): "Dismissal ",
                range(29, 34): "Divine  power",
                range(34, 40): "Flame  strike",
                range(40, 44): "Freedom  of movement",
                range(44, 47): "Holy  smite",
                range(47, 52): "Inflict  critical wounds",
                range(52, 57): "Magic  weapon, greater",
                range(57, 62): "Neutralize  poison",
                range(62, 65): "Order 's wrath",
                range(65, 69): "Poison ",
                range(69, 74): "Spell  immunity",
                range(74, 78): "Spike  stones",
                range(78, 81): "Summon  monster IV",
                range(81, 84): "Summon  nature's ally IV",
                range(84, 87): "Tongues ",
                range(87, 90): "Unholy  blight",
                range(90, 94): "Divination ",
                range(94, 97): "Planar  ally, lesser",
                range(97, 101): "Restoration ",
            }),
            'uncommon': RangedDictionary({
                range(1, 5): "Absorb  toxicity",
                range(5, 7): "Antiplant  shell",
                range(7, 12): "Aspect  of the stag",
                range(12, 16): "Aura  of doom",
                range(16, 22): "Ball  lightning",
                range(22, 26): "Blessing  of fervor",
                range(26, 29): "Blight ",
                range(29, 32): "Command  plants",
                range(32, 36): "Control  water",
                range(36, 40): "Debilitating  portent",
                range(40, 44): "Giant  vermin",
                range(44, 50): "Ice  storm",
                range(50, 56): "Imbue  with spell ability",
                range(56, 60): "Plague  carrier",
                range(60, 64): "Planar  adaptation",
                range(64, 68): "Protection  from energy, communal",
                range(68, 73): "Reincarnate ",
                range(73, 76): "Repel  vermin",
                range(76, 79): "Rusting  grasp",
                range(79, 84): "Scrying ",
                range(84, 88): "Sending ",
                range(88, 91): "Spiritual  ally",
                range(91, 94): "Thorn  body",
                range(94, 99): "Volcanic  storm",
                range(99, 101): "Symbol  of slowing",
            }),
        },
        5: {
            'common': RangedDictionary({
                range(1, 3): "Animal  growth",
                range(3, 5): "Atonement ",
                range(5, 8): "Baleful  polymorph",
                range(8, 12): "Break  enchantment",
                range(12, 17): "Breath  of life",
                range(17, 22): "Call  lightning storm",
                range(22, 26): "Command , greater",
                range(26, 31): "Cure  light wounds, mass",
                range(31, 35): "Death  ward",
                range(35, 38): "Disrupting  weapon",
                range(38, 43): "Inflict  light wounds, mass",
                range(43, 48): "Plane  shift",
                range(48, 54): "Righteous  might",
                range(54, 58): "Scrying ",
                range(58, 63): "Slay  living",
                range(63, 68): "Spell  resistance",
                range(68, 71): "Summon  monster V",
                range(71, 74): "Summon  nature's ally V",
                range(74, 76): "Tree  stride",
                range(76, 78): "Wall  of fire",
                range(78, 81): "Wall  of stone",
                range(81, 83): "Wall  of thorns",
                range(83, 88): "True  seeing",
                range(88, 92): "Commune ",
                range(92, 95): "Awaken ",
                range(95, 101): "Raise  dead",
            }),
            'uncommon': RangedDictionary({
                range(1, 4): "Air  walk, communal",
                range(4, 9): "Aspect  of the wolf",
                range(9, 12): "Blessing  of the salamander",
                range(12, 16): "Cleanse ",
                range(16, 22): "Commune  with nature",
                range(22, 25): "Contagion , greater",
                range(25, 29): "Control  winds",
                range(29, 32): "Dispel  chaos",
                range(32, 35): "Dispel  evil",
                range(35, 38): "Dispel  good",
                range(38, 41): "Dispel  law",
                range(41, 44): "Fickle  winds",
                range(44, 47): "Forbid  action, greater",
                range(47, 53): "Insect  plague",
                range(53, 56): "Life  bubble",
                range(56, 59): "Mark  of justice",
                range(59, 64): "Pillar  of life",
                range(64, 67): "Serenity ",
                range(67, 73): "Snake  staff",
                range(73, 77): "Spell  immunity, communal",
                range(77, 80): "Transmute  mud to rock",
                range(80, 83): "Transmute  rock to mud",
                range(83, 87): "Wind  blades",
                range(87, 91): "Stoneskin ",
                range(91, 93): "Hallow1 ",
                range(93, 95): "Symbol  of pain",
                range(95, 97): "Symbol  of sleep",
                range(97, 99): "Unhallow1 ",
                range(99, 100): "Hallow2 ",
                range(100, 101): "Unhallow2 ",
            }),
        },
        6: {
            'common': RangedDictionary({
                range(1, 6): "Bear 's endurance, mass",
                range(6, 12): "Blade  barrier",
                range(12, 17): "Bull 's strength, mass",
                range(17, 22): "Cat 's grace, mass",
                range(22, 28): "Cure  moderate wounds, mass",
                range(28, 33): "Dispel  magic, greater",
                range(33, 38): "Eagle 's splendor, mass",
                range(38, 44): "Find  the path",
                range(44, 48): "Fire  seeds",
                range(48, 56): "Harm ",
                range(56, 64): "Heal ",
                range(64, 70): "Heroes ' feast",
                range(70, 75): "Inflict  moderate wounds, mass",
                range(75, 79): "Liveoak ",
                range(79, 84): "Owl 's wisdom, mass",
                range(84, 88): "Summon  monster VI",
                range(88, 92): "Summon  nature's ally VI",
                range(92, 97): "Word  of recall",
                range(97, 101): "Planar  ally",
            }),
            'uncommon': RangedDictionary({
                range(1, 6): "Animate  objects",
                range(6, 10): "Antilife  shell",
                range(10, 16): "Banishment ",
                range(16, 20): "Cold  ice strike",
                range(20, 24): "Dust  form",
                range(24, 30): "Geas /quest",
                range(30, 34): "Ironwood ",
                range(34, 38): "Joyful  rapture",
                range(38, 43): "Move  earth",
                range(43, 47): "Plague  storm",
                range(47, 52): "Planar  adaptation, mass",
                range(52, 55): "Repel  wood",
                range(55, 60): "Sirocco ",
                range(60, 64): "Spellstaff ",
                range(64, 68): "Stone  tell",
                range(68, 71): "Swarm  skin",
                range(71, 75): "Tar  pool",
                range(75, 78): "Transport  via plants",
                range(78, 84): "Wind  walk",
                range(84, 87): "Create  undead",
                range(87, 91): "Glyph  of warding, greater",
                range(91, 93): "Undeath  to death",
                range(93, 96): "Symbol  of fear",
                range(96, 99): "Forbiddance ",
                range(99, 101): "Symbol  of persuasion",
            }),
        },
        7: {
            'common': RangedDictionary({
                range(1, 5): "Blasphemy ",
                range(5, 11): "Control  weather",
                range(11, 18): "Creeping  doom",
                range(18, 25): "Cure  serious wounds, mass",
                range(25, 29): "Dictum ",
                range(29, 34): "Ethereal  jaunt",
                range(34, 41): "Fire  storm",
                range(41, 45): "Holy  word",
                range(45, 51): "Inflict  serious wounds, mass",
                range(51, 56): "Regenerate ",
                range(56, 61): "Repulsion ",
                range(61, 66): "Scrying , greater",
                range(66, 70): "Summon  monster VII",
                range(70, 74): "Summon  nature's ally VII",
                range(74, 79): "Sunbeam ",
                range(79, 83): "Word  of chaos",
                range(83, 90): "Destruction ",
                range(90, 95): "Restoration , greater",
                range(95, 101): "Resurrection ",
            }),
            'uncommon': RangedDictionary({
                range(1, 9): "Animate  plants",
                range(9, 18): "Changestaff ",
                range(18, 25): "Circle  of clarity",
                range(25, 31): "Create  demiplane, lesser",
                range(31, 39): "Jolting  portent",
                range(39, 46): "Rampart ",
                range(46, 54): "Scouring  winds",
                range(54, 61): "Siege  of trees",
                range(61, 68): "Transmute  metal to wood",
                range(68, 77): "Vortex ",
                range(77, 84): "Waves  of ecstasy",
                range(84, 90): "Refuge ",
                range(90, 96): "Symbol  of stunning",
                range(96, 101): "Symbol  of weakness",
            }),
        },
        8: {
            'common': RangedDictionary({
                range(1, 9): "Antimagic  field",
                range(9, 15): "Cloak  of chaos",
                range(15, 24): "Cure  critical wounds, mass",
                range(24, 32): "Earthquake ",
                range(32, 39): "Finger  of death",
                range(39, 45): "Holy  aura",
                range(45, 52): "Inflict  critical wounds, mass",
                range(52, 60): "Reverse  gravity",
                range(60, 66): "Shield  of law",
                range(66, 74): "Spell  immunity, greater",
                range(74, 79): "Summon  monster VIII",
                range(79, 84): "Summon  nature's ally VIII",
                range(84, 90): "Sunburst ",
                range(90, 96): "Unholy  aura",
                range(96, 101): "Planar  ally, greater",
            }),
            'uncommon': RangedDictionary({
                range(1, 8): "Animal  shapes",
                range(8, 14): "Blood  mist",
                range(14, 19): "Control  plants",
                range(19, 25): "Create  demiplane",
                range(25, 32): "Dimensional  lock",
                range(32, 38): "Discern  location",
                range(38, 43): "Euphoric  tranquility",
                range(43, 50): "Frightful  aspect",
                range(50, 57): "Orb  of the void",
                range(57, 62): "Repel  metal or stone",
                range(62, 69): "Seamantle ",
                range(69, 76): "Storm  bolts",
                range(76, 84): "Whirlwind ",
                range(84, 89): "Create  greater undead",
                range(89, 96): "Symbol  of death",
                range(96, 101): "Symbol  of insanity",
            }),
        },
        9: {
            'common': RangedDictionary({
                range(1, 8): "Elemental  swarm",
                range(8, 16): "Energy  drain",
                range(16, 23): "Etherealness ",
                range(23, 31): "Gate ",
                range(31, 41): "Heal , mass",
                range(41, 49): "Implosion ",
                range(49, 59): "Miracle ",
                range(59, 66): "Shambler ",
                range(66, 74): "Shapechange ",
                range(74, 82): "Storm  of vengeance",
                range(82, 88): "Summon  monster IX",
                range(88, 94): "Summon  nature's ally IX",
                range(94, 101): "True  resurrection",
            }),
            'uncommon': RangedDictionary({
                range(1, 9): "Antipathy ",
                range(9, 16): "Clashing  rocks",
                range(16, 23): "Create  demiplane, greater",
                range(23, 32): "Foresight ",
                range(32, 40): "Overwhelming  presence",
                range(40, 48): "Polar  midnight",
                range(48, 57): "Soul  bind",
                range(57, 65): "Spell  immunity, greater",
                range(65, 72): "Summon  froghemoth",
                range(72, 81): "Winds  of vengeance",
                range(81, 88): "World  wave",
                range(88, 95): "Astral  projection",
                range(95, 101): "Sympathy ",
            }),
        }
    }
}

rnd_scrolls_grade = {
    #                range((spell level, caster level, type)
    "lesser minor": RangedDictionary({
        range(1, 16): (0, 1),
        range(16, 96): (1, 1),
        range(96, 101): (2, 3)
    }),
    "greater minor": RangedDictionary({
        range(1, 6): (0, 1),
        range(6, 36): (1, 1),
        range(36, 91): (2, 3),
        range(91, 101): (3, 5)
    }),
    "lesser medium": RangedDictionary({
        range(1, 11): (2, 3),
        range(11, 56): (3, 5),
        range(56, 101): (4, 7)
    }),
    "greater medium": RangedDictionary({
        range(1, 21): (3, 5),
        range(21, 61): (4, 7),
        range(61, 101): (5, 9)
    }),
    "lesser major": RangedDictionary({
        range(1, 31): (4, 7),
        range(31, 66): (5, 9),
        range(66, 91): (6, 11),
        range(91, 101): (7, 13)
    }),
    "greater major": RangedDictionary({
        range(1, 6): (6, 11),
        range(6, 36): (7, 13),
        range(36, 71): (8, 15),
        range(71, 101): (9, 17)
    })
}

rnd_scrolls_type = RangedDictionary({
    range(1, 46): ("common", "arcane"),
    range(46, 61): ("uncommon", "arcane"),
    range(61, 91): ("common", "divine"),
    range(91, 101): ("uncommon", "divine")
})


def get_scroll(grade):
    d100 = lambda: (random.randint(1, 100))

    spell_lvl, caster_lvl = rnd_scrolls_grade[grade][d100()]
    scroll_rarity, scroll_type = rnd_scrolls_type[d100()]

    scroll = rnd_scrolls[scroll_type][spell_lvl][scroll_rarity][d100()]

    # TO-DO: IMPLEMENT CASTER LEVEL

    return scroll

if __name__ == '__main__':
    test_range100(rnd_scrolls_grade)
    test_range100(rnd_scrolls)

    for g in ["lesser minor", "greater minor", "lesser medium",
              "greater medium", "lesser major", "greater major"]:
        print("{}: {}".format(g, get_scroll(g)))
